### PR TITLE
Add failing test for `import * from ...`

### PR DESCRIPTION
**Pull request by benadamstyles**
`import * as x from ...` appears to be creating false positives, I made a failing test to show what's going wrong. I'd love to help out with this but I'm not sure where to start, should I be looking at the babel docs?

### CODE REVIEW

**Comment by benadamstyles** [comment]
The result I expect from this new test is that there is a single unused export, `second`, which is exported from `test/import-all/exports.js`. I don't know if it's even possible to get this level of granularity from babel though!

**Comment by yamafaktory** [comment]
@benadamstyles Thanks a lot for this PR, I'll have a look at it asap!

**Comment by yamafaktory** [comment]
@benadamstyles I've quite a lot of refactoring for some other issues and this is now addressed in another branch. Sorry for the long - very long - delay. I'll soon release a new version and close this PR.

**Comment by yamafaktory** [comment]
@benadamstyles I've finally released a new version that supersedes this PR. Thanks for your work and for discovering that issue 🍻 !

**Comment by benadamstyles** [comment]
@yamafaktory Great stuff, thanks! Just trying it now, I'm getting this error:

```
TypeError: Cannot destructure property `imports` of 'undefined' or 'null'.
    at namespaceImports.map (/Users/ben/Dev/Git/meals/node_modules/shrimpit/lib.js:318:41)
```

It's at [this line](https://github.com/yamafaktory/shrimpit/blob/master/lib.js#L318), because `getTreeProp()` is returning `null` or `undefined`. Any idea why this might be happening?

**Comment by yamafaktory** [comment]
@benadamstyles Thanks for the report! I'll have a look at it!

**Comment by yamafaktory** [comment]
@benadamstyles The latest version should have addressed your issue!

**Comment by benadamstyles** [comment]
It does, thanks so much!

**Pull request closed without merging**
